sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - mvn clean
install:
  - mvn install -Dgpg.skip=true -DskipTests=true
notifications:
  email:
    recipients:
      - bogdan.livadariu@gmail.com
